# Site settings
title: "Manuel A. Llanos, Ph.D."
description: >-
  Staff Scientist at The Scripps Research Institute, La Jolla, CA.
  Computational drug discovery, structure-based drug design, and molecular simulations.
minimal_mistakes_skin: "default"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
timezone: America/Los_Angeles

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-D4KB31TQQS" # Replace this with your ID, or delete
    anonymize_ip         : true

author:
  name   : "Manuel A. Llanos, Ph.D."
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I like molecules 💊 👨‍🔬  🧉 🇦🇷  \n    Drug discovery\ | Computational Biophysics"
  location: "La Jolla, CA"
  links:
    - label: "Forli Lab"
      icon: "fas fa-fw fa-flask"
      url: "https://forlilab.org"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/manuel-llanos"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mllanos@scripps.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mallanos"
    - label: "ORCID"
      icon: "ai ai-fw ai-orcid"
      url: "https://orcid.org/0000-0002-9120-4951"

footer:
  links:
    - label: "Forli Lab"
      icon: "fas fa-fw fa-flask"
      url: "https://forlilab.org"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/manuel-llanos"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mallanos"
    - label: "ORCID"
      icon: "ai ai-fw ai-orcid"
      url: "https://orcid.org/0000-0002-9120-4951"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
